name: OpenWebRX+
version: 1.2.73
slug: openwebrx
description: OpenWebRX+ with Digital modes (SoftMBE), including DMR, D-Star, YSF, FreeDV, DRM, NXDN, etc.
url: https://www.openwebrx.de/
image: docker.io/slechev/openwebrxplus-softmbe
startup: services
webui: http://[HOST]:[PORT:8073]/
startup: services
init: false
usb: true
arch:
- amd64
environment:
  OPENWEBRX_ADMIN_USER: admin
  OPENWEBRX_ADMIN_PASSWORD: admin
ports:
  8073/tcp: 8073
ports_description:
  8073/tcp: Webserver
