name: Dump1090
version: latest
slug: piaware
description: Run dump1090-fa (Flightaware fork) quickly and easily with Docker!
url: https://de.flightaware.com/adsb/
image: docker.io/jraviles/dump1090
ingress: true
ingress_stream: true
startup: services
ingress_port: 8080
startup: services
init: false
panel_icon: mdi:airplane
usb: true
arch:
- amd64
ports:
  8080/tcp: null
