name: BosMon
version: 2023.14_patch3
slug: bosmon
description: BosMon ist ein innovatives Programm zum Dekodieren von ZVEI, FMS und Pocsag Telegrammen.
url: https://github.com/timniklas/addon-bosmon
image: ghcr.io/timniklas/addon-bosmon
ingress: true
ingress_stream: true
startup: services
panel_icon: mdi:alarm-light
arch:
- amd64
options:
  display_resolution: 1280x720
schema:
  key_name: "match([a-zA-Z0-9]+)"
  key_serial: "match([a-zA-Z0-9]{5}-[a-zA-Z0-9]{5}-[a-zA-Z0-9]{5}-[a-zA-Z0-9]{5}-[a-zA-Z0-9]{5})"
  display_resolution: "match([0-9]+x[0-9]+)"
ports:
  80/tcp: null
  8099/tcp: null
  5901/tcp: null
ports_description:
  80/tcp: BosMon Webserver
  8099/tcp: HTTP without authentication (danger!)
  5901/tcp: VNC without authentication (danger!)
