name: Meshtastic Client
version: v0.0.3
slug: meshtastic-network-management-client
description: A Meshtastic desktop client, allowing simple, offline deployment and administration of an ad-hoc mesh communication network.
url: https://github.com/timniklas/addon-meshtastic-network-management-client
image: ghcr.io/timniklas/addon-meshtastic-network-management-client
ingress: true
ingress_stream: true
startup: services
panel_icon: mdi:access-point
arch:
- amd64
options:
  display_resolution: 1024x768
schema:
  display_resolution: "match([0-9]+x[0-9]+)"
