name: BosMon RTL-SDR
version: v0.2
slug: bosmon-rtlsdr
description: RTL-SDR Pocsag receiver
url: https://github.com/timniklas/addon-bosmon-rtlsdr
image: ghcr.io/timniklas/addon-bosmon-rtlsdr
startup: services
usb: true
arch:
- amd64
options:
  frequency: 439.9875M
  bosmon_url: "http://"
schema:
  frequency: "match([0-9_]+[.][0-9_]+M)"
  bosmon_url: "url"
  bosmon_username: "match([a-zA-Z0-9_]+)"
  bosmon_password: "password"
  bosmon_endpoint: "match([a-zA-Z0-9_]+)"
